### PR TITLE
Tweak dark colorscheme

### PR DESCRIPTION
**Pull request by teoljungberg**
Background:
This PR tweaks the dark version of whitescale to increase the contrast
between normal and bold text, as well as tweaking the background color
by making it a bit greyer than black.

### CODE REVIEW

**Comment by teoljungberg** [comment]
I don't know if @klaaspieter still uses this, but I'm pinging you anyhow.

**Comment by teoljungberg** [comment]
Example from my dotfiles

Light. Which has good contrast between the gray for comments, the normal text color, and the bold. This is left unchanged.
Screen Shot 2020-09-15 at 12 05 46


Dark. Which now is easier to distinguish between normal, bold, and gray.
Screen Shot 2020-09-15 at 12 05 43

**Comment by teoljungberg** [comment]
By the looks of https://github.com/klaaspieter/dotfiles/commit/94a429169c10ce6aba0549c83d9668c76239ede5, he does not.

**Comment by klaaspieter** [comment]
I do not, but this looks good to me 😄

**Comment by teoljungberg** [comment]
Do you want to try it out before I merge it in that case @klaaspieter?

**Comment by teoljungberg** [comment]
Whatcha think @klaaspieter ?

**Comment by klaaspieter** [comment]
You're just trying to get me back to working without a 🎄 in my editor aren't you? 😂 

It's up to you really but I don't see myself changing my dotfiles again soon 😛

**Comment by teoljungberg** [comment]
Fine be me, just wanted to check if you wanted to have any input before I rolled with this.

I'm thinking about if I should dim the comments a bit more.

**Pull request merged**
