### PR TITLE
Test highlighting types as bold + italic

### PR DESCRIPTION
**Pull request by teoljungberg**

### CODE REVIEW

**Comment by teoljungberg** [comment]
What do you think @klaaspieter ?

**Comment by klaaspieter** [comment]
Not a huge fan. Partially because for some reason the `struct` keyword in Swift is `Type`, but I'm also not a fan of types looking slanted like that... 🤔 

image

For what it's worth I had to run this outside of tmux because for some reason my `$TERM` in tmux doesn't support italics. Took me a while to discover 😂. The point being if you enable this tmux will not render it for me anyway 😜

**Comment by teoljungberg** [comment]
I'm going to run it for a week and see how I feel.

**Comment by teoljungberg** [comment]
And @klaaspieter if you want to get italics in your terminal:

https://github.com/teoljungberg/dotfiles/commit/abe18b9c274ad000eb7e62fa318ac1623ee8bd01

**Comment by teoljungberg** [comment]
I'm not feeling this. I'm closing.

**Pull request closed without merging**
